// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDodrT7suXHuA-tg9xgmqDcSppfweoqHHY',
    appId: '1:729272461010:web:1be3875e887103c9a1ef0b',
    messagingSenderId: '729272461010',
    projectId: 'partnerup-993d9',
    authDomain: 'partnerup-993d9.firebaseapp.com',
    storageBucket: 'partnerup-993d9.appspot.com',
    measurementId: 'G-N98GSBZ9R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ_UhF9-I8opqK1KWWWocVco0Ya8FuwYI',
    appId: '1:729272461010:android:14bbc985410781faa1ef0b',
    messagingSenderId: '729272461010',
    projectId: 'partnerup-993d9',
    storageBucket: 'partnerup-993d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGvB74KVy0-qeU99lXSNUNsVIrpEDKdGI',
    appId: '1:729272461010:ios:81edfd056176c1c0a1ef0b',
    messagingSenderId: '729272461010',
    projectId: 'partnerup-993d9',
    storageBucket: 'partnerup-993d9.appspot.com',
    iosBundleId: 'com.example.partnerUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGvB74KVy0-qeU99lXSNUNsVIrpEDKdGI',
    appId: '1:729272461010:ios:81edfd056176c1c0a1ef0b',
    messagingSenderId: '729272461010',
    projectId: 'partnerup-993d9',
    storageBucket: 'partnerup-993d9.appspot.com',
    iosBundleId: 'com.example.partnerUp',
  );
}
